[package]
name = "dirreader"
version = "0.1.0"
authors = ["kkapp <konrad.p.kapp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
